name: Update database

on:
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/sql-action@v2.2.1
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './sql/Restaurant.sql'
          action: 'publish'
